name: Mise a jour automatique de la Veille

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-veille:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Exécuter le script
        run: python script.py

      - name: Enregistrer les modifications
        run: |
          git config --global user.name 'Bot Veille BTS'
          git config --global user.email 'bot@github.com'
          git add README.md
          git commit -m "Auto: Mise à jour du tableau de veille" || exit 0
          git push
